#!/bin/sh
# --ignore-matching-lines

# Bug reported by Vincent Lefevre in <http://bugs.gnu.org/16864>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

fail=0

cat <<'EOF' >a
1a
2
3a
4
5
6
EOF

cat <<'EOF' >b
1b
2
3b
4
5
6
7
EOF

cat <<'EOF' >exp
@@ -1,6 +1,7 @@
-1a
+1b
 2
-3a
+3b
 4
 5
 6
+7
EOF

diff -u --ignore-matching-lines 3 a b >out 2>err
test $? = 1 || fail=1
sed 1,2d out >outtail || framework_failure+
compare exp outtail || fail=1

Exit $fail
